const BOOKLIST = [
    { 
        id: 1,
        title: 'Pharmacology: a Patient-centered Nursing Process Approach 11th Edition',
        author: 'Linda E. Mc Cuistion, Kathleen Vuljoin-DiMaggio, Mary B. Winton, Jennifer J. Yeager',
        publisher: 'Elsevier Pte Ltd',
        image: require('./assets/img1.png'),
        language: 'English',
        copyright: 2023,
        subject: 'Pharmacology 2. Nursing',
        edition: '11th Edition',
        volume: '',
        area: 'Para-medical Section',
        isbn: '978-981-492-088-9',
    },
    { 
        id: 2,
        title: 'Kozier & Erb’s Fundamentals of Nursing: Concepts, Process, and Practice Eleventh Edition Volume 1',
        author: 'Audrey Berman, Shirlee K. Synder, Geraldyn Frandsen',
        publisher: 'Pearson Education South Asia Pte Ltd.',
        image: require('./assets/img2.png'),
        language: 'English',
        copyright: 2022,
        subject: 'Nursing',
        edition: '11th Edition',
        volume: 'Volume 1',
        area: 'Para-medical Section',
        isbn: '978-981-31-3744-8',
    },
    { 
        id: 3,
        title: 'Kozier & Erb’s Fundamentals of Nursing: Concepts, Process, and Practice Eleventh Edition Volume 2',
        author: 'Audrey Berman, Shirlee K. Synder, Geraldyn Frandsen',
        publisher: 'Pearson Education South Asia Pte Ltd.',
        image: require('./assets/img3.png'),
        language: 'English',
        copyright: 2022,
        subject: 'Nursing',
        edition: '11th Edition',
        volume: 'Volume 1',
        area: 'Para-medical Section',
        isbn: '978-981-31-3744-8',
    },
    { 
        id: 4,
        title: 'Seeley Essentials of Anatomy & Physiology Eleventh Edition',
        author: 'Cinnamon VaPutte, Jennifer Regan, Andrew Russo',
        publisher: 'Mc Graw-Hill',
        image: require('./assets/img4.png'),
        language: 'English',
        copyright: 2022,
        subject: '1. Human anatomy 2. Human physiology',
        edition: '11th Edition',
        volume: '',
        area: 'Para-medical Section',
        isbn: '978-1-265-34844-1',
    },
    { 
        id: 5,
        title: 'Nursing as Educator: Principles of Teaching and Learning for Nursing Practice Six Edition',
        author: 'Susan B. Bastable',
        publisher: 'Burling, Ma: Jones & Bartlett Learning',
        image: require('./assets/img5.png'),
        language: 'English',
        copyright: 2023,
        subject: '1. Health education 2. Nursing education -- methods-- nurses instruction',
        edition: 'Sixth Edition',
        volume: '',
        area: 'Para-medical Section',
        isbn: '978-1-284-26436-4',
    },
    { 
        id: 6,
        title: 'Essentials of Nursing Research: Appraising Evidence for Nursing Practice Tenth Edition',
        author: 'Denise F. Polit, Cheryl Tatano Beck',
        publisher: 'Wolters Kluwer',
        image: require('./assets/img6.png'),
        language: 'English',
        copyright: 2022,
        subject: '1. Nursing -- Research -- methodology 2. Nursing -- Research -- Evaluation',
        edition: 'Tenth Edition',
        volume: '',
        area: 'Para-medical Section',
        isbn: '978-1-9751-8981-5',
    },
    { 
        id: 7,
        title: 'Nursing Informatics and the Foundation of Knowledge Fifth Edition',
        author: 'Dee McGonigle, Kathleen Garver Mastrian',
        publisher: 'Burling, Ma: Jones & Bartlett Learning',
        image: require('./assets/img7.png'),
        language: 'English',
        copyright: 2022,
        subject: '1. Nursing informatics',
        edition: 'Fifth Edition',
        volume: '',
        area: 'Para-medical Section',
        isbn: '978-1-284-28350-1',
    },
    { 
        id: 8,
        title: 'Disaster Nursing and Emergency Preparedness: for Chemical, Biological, and Radiological Terrorism and other Hazards Fourth Edition',
        author: 'Tener Goodwin Veenema',
        publisher: 'New York, NY: Springer Publishing Company',
        image: require('./assets/img8.png'),
        language: 'English',
        copyright: 2019,
        subject: '1. Disaster nursing -- Handbooks, manuals, etc. 2Emergency nursing -- Handbooks, manuals, etc',
        edition: 'Fourth Edition',
        volume: '',
        area: 'Para-medical Section',
        isbn: '978-971-98-1747-5',
    },
    { 
        id: 9,
        title: 'Community and Public Health Nursing 2nd Philippine Edition',
        author: 'Mary A. Nies, Melanie McEwen, Earl Francis R. Sumile',
        publisher: 'Elsevier Pte Ltd',
        image: require('./assets/img9.png'),
        language: 'English',
        copyright: 2020,
        subject: '1. Community health nursing 2. Public health nursing',
        edition: '2nd Philippine Edition',
        volume: '',
        area: 'Para-medical Section',
        isbn: '978-981-4865-03-6',
    },
    { 
        id: 10,
        title: 'Psychiatric-Mental Health Nursing Ninth Edition',
        author: 'Sheila L. Videbeck',
        publisher: ' Wolters Kluwer',
        image: require('./assets/img10.png'),
        language: 'English',
        copyright: 2023,
        subject: '1. Psychiatric nursing',
        edition: 'Ninth Edition',
        volume: '',
        area: 'Para-medical Section',
        isbn: '978-1-9752-2248-2',
    },
];

export default BOOKLIST;